# Generated by Django 4.1.1 on 2022-11-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_have_size_product_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='semester',
            new_name='size',
        ),
    ]
