# Generated by Django 4.1.1 on 2022-11-23 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='sizestockL',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='sizestockM',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='sizestockS',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
