# Generated by Django 4.1.1 on 2022-11-23 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_size_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nonsizestock',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
