# Generated by Django 4.1.1 on 2022-11-11 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='phone_number',
        ),
    ]
