# Generated by Django 4.1.1 on 2022-11-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_rename_userdetails_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phone_number',
        ),
    ]
