# Generated by Django 4.1.1 on 2022-11-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
