# Generated by Django 4.1.1 on 2022-11-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Addressfield',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Email_Address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Town',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='firstname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='lastname',
            new_name='town',
        ),
    ]
