# Generated by Django 4.1.1 on 2022-11-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_rename_addressfield_address_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
