# Generated by Django 4.1.1 on 2022-12-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coupon',
        ),
    ]
